---
title: "Practica 6"
author: "Juan Llivisaca"
date: "2023-10-17"
output: word_document
---

#Anova 

```{r}
library(PASWR)
datos <-  Drosophila
??Drosophila

# Anova 
# Ho: Media de la fecundidad de los huevos puestos en el grupo de resistant es igual a la media de la fecundidad de los huevos puestos por el grupo Susceptible y es igual a Media de la fecundidad de los huevos puestos en el grupo de Noselected
#Ha : al menos una media es diferente
# alfa = 0.05 

# Estadístico de prueba 
# F 

modelo.1 <-  aov(datos$Fecundity ~ datos$Line)
summary(modelo.1)
# F = 8.666 
# Decisión

# P valor 

# 0.000424

# Comparo el p valor con el alfa 
# Rechazo Ho

oneway.plots(datos$Fecundity, datos$Line)


```


#Comparaciones multiples

```{r}
library(asbio)
(pairw.anova(x=Line, y=Fecundity, conf.level = 0.95, method="tukey")) # COmparación con Tukey
(pairw.anova(x=Line, y=Fecundity, conf.level = 0.95, method="lsd")) # COmparación con LSD
(pairw.anova(x=Line, y=Fecundity, conf.level = 0.99, method="scheffe")) # COmparación con Sheffe


```


#Supuestos del anova

```{r}
# Normalidad 
# Prueba de normalidad 
# Kolmogorov- Simirnov (datos son mayores a 50)
# Anderson Darling (datos son mayores a 50)
# Shapiro - Wilks (datos son menores a 50)
# Los datos en rangos en clases, 
# # Chi cuadrado 
# cuando los datos son independientes, son univariantes. 

# Kolmogorov 

library(nortest)

lillie.test(modelo.1$residuals)

# Homocedasticidad, igualdad de varianzas
library(lmtest)

hmctest(modelo.1$residuals ~ datos$Line)

plot(modelo.1)

# Linealidad 

regresion <-  lm(modelo.1$residuals ~ datos$Line)
summary(regresion)

# Prueba de Ramsey
library(lmtest)
residuos <-  modelo.1$residuals

reset(modelo.1)

```
#Maquinas

```{r}
# Ingreso datos
library(readr)
maquina <- read_csv("Base Flexim.csv")
attach(maquina)
# Anova

modelo.maquin <-  aov(maquina$Tiempo_transformado ~ Maquina)
summary(modelo.maquin)

#maquina$s <- as.numeric(maquina$s) Para cambiar los valores de la columna S de carácter a numérico.


```

```{r}
# Supuestos del modelo

# Normalidad 
# Prueba de normalidad 
# Kolmogorov- Simirnov (datos son mayores a 50)
# Anderson Darling (datos son mayores a 50)
# Shapiro - Wilks (datos son menores a 50)
# Los datos en rangos en clases, 
# # Chi cuadrado 
# cuando los datos son independientes, son univariantes. 

# Kolmogorov 

library(nortest)

lillie.test(modelo.maquin$residuals)

# No cumple el supuesto 

maquina <-  maquina[order(maquina$Maquina),] # Ordenar datos

maquina$Tiempo_transformado <-  sqrt(maquina$s) 

# Homocedasticidad, igualdad de varianzas
library(lmtest)

hmctest(modelo.1$residuals ~ datos$Line)

plot(modelo.1)

# Linealidad 

regresion <-  lm(modelo.1$residuals ~ datos$Line)
summary(regresion)

# Prueba de Ramsey
library(lmtest)
residuos <-  modelo.1$residuals

reset(modelo.1)

```

```{r}
peso <- c(15.16,28.99,16.95,29.61,34.61,20.69,17.39,29.94,22.79,30.86,14.00,
38.72,23.29,17.00,35.40,19.32,29.88)
# g= tilapias Gregori; s=tilapias Santafe
especie <- c('s',rep('g',8),rep('s',8))
# Prueba gráfica de homogeneidad e igualdad de medias #
boxplot(peso ~ especie)
# Gráfico de normalidad #
qqnorm(peso)
qqline(peso)

# Prueba parámetrica de normalidad #
shapiro.test(peso)

# Prueba de igualdad de medias #
t.test(peso~especie,var.equal=T,alternative="greater")
```
```{r}
###############
# Ejemplo 2.2 #
###############
# ¿Se puede suponer que las varianzas son +/- iguales? #
var.test(peso~ especie=='g')
```

```{r}
#Prueba T multivariada
###############
# Ejemplo 2.7 #
###############
# Lectura de datos #
agente.osmo <- c(rep('SC',6),rep('SS',6)) # SC = Sacarosa Cristalina,
#SS = Sal Sólida
brix <- c(17.0,17.5,17.2,21.0,20.5,20.7,30.0,29.0,29.5,31.0,31.0,30.0)
PH <- c(5.05,5.07,5.02,5.15,5.17,5.12,4.21,4.24,4.18,4.13,4.16,4.18)
osmo <- as.data.frame(agente.osmo)
osmo$brix <- brix
osmo$PH <- PH

# Prueba T^2 de Hotelling #
library(Hotelling)
library(corpcor)
split.data <- split(osmo[,-1],osmo$agente.osmo)
x <- split.data[[1]]
y <- split.data[[2]]

S <- 1/10*(5*cov(x) + 5*cov(y))
S <- (5*cov(x) + 5*cov(y))
T.1 <- 36/12*cbind(mean(x$brix)-mean(y$brix),mean(x$PH)-mean(y$PH))%*%solve(S)%*%rbind(mean(x$brix)-mean(y$brix),mean(x$PH)-mean(y$PH))
T.1
ST <- hotelling.stat(x, y)
ST
fit <- hotelling.test(brix+PH ~ agente.osmo, data=osmo)
fit
# comparación cuando no hay normalidad

 kruskal.test(peso~ especie=='g')
 pairwise.wilcox.test(x = peso, g = especie, p.adjust.method = "holm" )
```
```{r}
##################
### Ejemplo 5.8 ##
##################

library(pwr) # pwr.anova.test, instalar paquete si no se tiene
# k: número de tratamientos, n: número de replicas, f=phi/sqrt(n)
# con esta función se averigua la potencia para un k y un n dados
pwr.anova.test(k=4,n=5,f=2/sqrt(5),sig.level=0.05)
# con esta función se averigua el n para una potencia dada
pwr.anova.test(f=2/sqrt(5),k=4,power=0.80,sig.level=0.05)

phi <- seq(0, 4, 0.01)
pot <- pwr.anova.test(k = 4, n = 5, f = phi/sqrt(5), sig.level = 0.05, power = NULL)$power
beta=1-pot
# Curva característica de operación
plot(phi,beta,type='l')
abline(v=2,lty=2)

##################
### Ejemplo 5.9 ##
##################

# Se encuentra f y después phi
pwr.anova.test(k=4,n=15,power=0.80,sig.level=0.05)
phi <- 0.4414577*sqrt(15)
phi

# phi^2=0.1086r
r <- phi^2/0.1086
pwr.anova.test(k=4,n=round(r),f=sqrt(0.1086),sig.level=0.05) # r=27
pwr.anova.test(k=4,f=sqrt(0.1086),power=0.80,sig.level=0.05) # r=27

###################
### Ejemplo 5.10 ##
###################

# Delta*=0.75, 1.0, 1.25, phi=Delta*^2*r/(2t)
phi1 <- c(0.75,1,1.25)/sqrt(2*4)

# 1-beta=0.70
pwr.anova.test(k=4,f=phi1[1],power=0.7,sig.level=0.05)
pwr.anova.test(k=4,f=phi1[2],power=0.7,sig.level=0.05)
pwr.anova.test(k=4,f=phi1[3],power=0.7,sig.level=0.05)

# 1-beta=0.80
pwr.anova.test(k=4,f=phi1[1],power=0.8,sig.level=0.05)
pwr.anova.test(k=4,f=phi1[2],power=0.8,sig.level=0.05)
pwr.anova.test(k=4,f=phi1[3],power=0.8,sig.level=0.05)
# 1-beta=0.90
pwr.anova.test(k=4,f=phi1[1],power=0.9,sig.level=0.05)
pwr.anova.test(k=4,f=phi1[2],power=0.9,sig.level=0.05)
pwr.anova.test(k=4,f=phi1[3],power=0.9,sig.level=0.05)
```

